=== DylanRodgers98/GraphGrammarPCG/Assets/GenGra/GenGra.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="https://github.com/DylanRodgers98/GraphGrammarPCG"
  targetNamespace="https://github.com/DylanRodgers98/GraphGrammarPCG"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified">

  <xs:complexType name="GenGraType">
    <xs:sequence>
      <xs:element name="graphs" type="GraphsType" />
      <xs:element name="grammar" type="GrammarType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="GraphsType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="graph"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="GraphType">
    <xs:sequence>
      <xs:element name="nodes" type="NodesType" />
      <xs:element name="edges" type="EdgesType" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="NodesType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="node" type="NodeType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="NodeType">
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="symbol" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="EdgesType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="edge" type="EdgeType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="EdgeType">
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="source" type="xs:string" use="required" />
    <xs:attribute name="target" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="GrammarType">
    <xs:sequence>
      <xs:element name="startGraph" type="StartGraphType" />
      <xs:element name="rules" type="RulesType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="StartGraphType">
    <xs:attribute name="ref" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="RulesType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="rule" type="RuleType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="RuleType">
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="source" type="xs:string" use="required" />
    <xs:attribute name="target" type="xs:string" use="required" />
  </xs:complexType>

  <xs:element name="gengra" type="GenGraType">
    <xs:unique name="graph_id_unique">
      <xs:selector xpath=".//graphs/graph"/>
      <xs:field xpath="@id"/>
    </xs:unique>
  
    <xs:key name="graph_id_key">
      <xs:selector xpath=".//graphs/graph"/>
      <xs:field xpath="@id"/>
    </xs:key>
  
    <xs:keyref name="start_graph_ref" refer="graph_id_key">
      <xs:selector xpath=".//grammar/startGraph"/>
      <xs:field xpath="@ref"/>
    </xs:keyref>

    <xs:unique name="rule_id_unique">
      <xs:selector xpath=".//rules/rule"/>
      <xs:field xpath="@id"/>
    </xs:unique>

    <xs:keyref name="rule_source_ref" refer="graph_id_key">
      <xs:selector xpath=".//graphs/graph"/>
      <xs:field xpath="@source"/>
    </xs:keyref>

    <xs:keyref name="rule_target_ref" refer="graph_id_key">
      <xs:selector xpath=".//graphs/graph"/>
      <xs:field xpath="@target"/>
    </xs:keyref>
  </xs:element>

  <xs:element name="graph" type="GraphType">
    <xs:unique name="node_id_unique">
      <xs:selector xpath=".//nodes/node"/>
      <xs:field xpath="@id"/>
    </xs:unique>

    <xs:unique name="edge_id_unique">
      <xs:selector xpath=".//edges/edge"/>
      <xs:field xpath="@id"/>
    </xs:unique>

    <xs:key name="node_id_key">
      <xs:selector xpath=".//nodes/node"/>
      <xs:field xpath="@id"/>
    </xs:key>

    <xs:keyref name="edge_source_ref" refer="node_id_key">
      <xs:selector xpath=".//edges/edge"/>
      <xs:field xpath="@source"/>
    </xs:keyref>

    <xs:keyref name="edge_target_ref" refer="node_id_key">
      <xs:selector xpath=".//edges/edge"/>
      <xs:field xpath="@target"/>
    </xs:keyref>
  </xs:element>

</xs:schema>

=== DylanRodgers98/GraphGrammarPCG/Assets/GenGra/gengra-example.xml
<?xml version="1.0" encoding="UTF-8"?>
<gengra xmlns="https://github.com/DylanRodgers98/GraphGrammarPCG"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://github.com/DylanRodgers98/GraphGrammarPCG
		file:///C:/Users/dylan/Dropbox/Uni/Year 3/Project/Code/Procedural Generation - Final Year Project/Assets/GenGra/GenGra.xsd">
	
	<graphs>
		<graph id="G1">
			<node id="n0" symbol="A"/>
			<node id="n1" symbol="B"/>
			<node id="n2" symbol="C"/>
			<node id="n3" symbol="D"/>
			<node id="n4" symbol="E"/>
			<node id="n5" symbol="F"/>
			<node id="n6" symbol="G"/>
			<node id="n7" symbol="H"/>
			<node id="n8" symbol="I"/>
			<node id="n9" symbol="J"/>
			<node id="n10" symbol="K"/>
			<edge source="n0" target="n2"/>
			<edge source="n1" target="n2"/>
			<edge source="n2" target="n3"/>
			<edge source="n3" target="n5"/>
			<edge source="n3" target="n4"/>
			<edge source="n4" target="n6"/>
			<edge source="n6" target="n5"/>
			<edge source="n5" target="n7"/>
			<edge source="n6" target="n8"/>
			<edge source="n8" target="n7"/>
			<edge source="n8" target="n9"/>
			<edge source="n8" target="n10"/>
		  </graph>
	</graphs>
	
	<grammar>
		<startGraph ref="G1"/>
		<rules>
			<rule source="G1" target="G2"/>
		</rules>
	</grammar>
	
</gengra>
